### ISSUE TITLE
Slime / magma cube loot tables being replaced instead of injected

### ISSUE THREAD

**Issue by 13579resu** [frikinjay/morefrogs#12]
While replacing these loot tables is fine if you're using this mod on its own, it leads to conflicts whenever there's another mod that alters the drops of these mobs. For example, it is impossible to get reliquary slime pearls while this mod is present. 

This seems to be the source of this issue, located at morefrogs-1.19.x-1.1.1-forge.jar\data\minecraft\loot_tables\entities\slime.json:
![Screenshot_2713](https://user-images.githubusercontent.com/42251064/200948602-a129237c-7d96-49a3-873a-abaff025b194.png)

**Comment by frikinjay** [comment]
Wasnt aware I was replacing, mightve been left during dev. Thanks for letting me know i'll fix it in a couple mins.

**Comment by frikinjay** [comment]
Fixed in forge 1.1.1a and fabric 1.2.3b

**Comment by 13579resu** [comment]
From my testing, the issue at hand still seems to persist.

These are the results from testing with just these two mods:
![Screenshot_2729](https://user-images.githubusercontent.com/42251064/202786187-334a75ac-a43c-4132-b1fb-34bdf9b385ea.png)

--- With more frogs ---
No slime pearls are dropped despite having the enchantment "Severing" for increased drop chances of said item:
![Screenshot_2728](https://user-images.githubusercontent.com/42251064/202786372-720baf9f-c168-4f6a-84fe-5eb51fd1a6fb.png)

-- Without more frogs ---
Slime pearls drop from about every two slimes

![Screenshot_2732](https://user-images.githubusercontent.com/42251064/202786604-687951c0-dbb2-41fc-ad99-f788534a46f3.png)

--- Without "Severing" enchantment ---
With more frogs installed no slime pearls are dropping
![Screenshot_2730](https://user-images.githubusercontent.com/42251064/202786708-162601b8-4754-47a4-ba18-98578434611d.png)

Without more frogs installed it takes just 5 slimes for a pearl to drop
![Screenshot_2731](https://user-images.githubusercontent.com/42251064/202786855-025464ab-7db5-4316-b225-490b1efa3bd1.png)

**Comment by Gbergz** [comment]
Still isn't fixed apparently as stated in #13

**Comment by InfinitysDaughter** [comment]
Still an issue as of 12/23. Its also interfering with swampier swamps froglights. I've tested with just the two frog mods and when I have just SS the frogs drop their lights when killing magma cubes but as soon as I add MF they stop.
